#!/usr/bin/env bash

psql -U "$POSTGRES_USER" -c "CREATE DATABASE $POSTGRES_LOGIN_SERVICE_DB;" "$POSTGRES_DB"
psql -U "$POSTGRES_USER" -c "CREATE DATABASE $POSTGRES_TRAVELLER_SERVICE_DB;" "$POSTGRES_DB"

psql -U "$POSTGRES_USER" -c "\l+" "$POSTGRES_DB"


 
